### ISSUE TITLE
Apply middleware to all routes

### ISSUE THREAD

**Issue by m3l7** [stephens2424/muxchain#4]
Hello,
I'm completely new to golang, so my question could be quite silly.

Is there a way to apply a middleware to all routes?
Of course, I can do something like:

      muxchain.Chain("/",handler,.....)
      muxchain.Chain("/second",handler,....)

I'm wondering if there's a way to avoid the handler duplication.
thanks

**Comment by stephens2424** [comment]
You can wrap handlers in other handlers and you can make your routing happen "behind" the middleware:

```
// set up your route specific handlers
m := http.NewServeMux()
m.Handle("/", indexHandler)
m.Handle("/second", secondHandler)

// wrap these routed handlers in a function that does "universal" processing
wrappedHandler := http.HandlerFunc(func (w http.ResponseWriter, r *http.Request) {
    // do stuff with w and r
    m.ServeHTTP(w, r)
})

// serve from the wrapped handler
http.ListenAndServe(":80", wrappedHandler)
```

This approach works with both the standard library (as I've done above) as well as with helper libraries like this one. You can do it multiple times, too, if you need to have, for instance, some request paths gzipped, some not, but all of them logged.
